cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('',views.detail , name='detail'),
    path('add/<int:product_id>/',views.add_cart , name='add_cart'),
    path('remove/<int:product_id>/' , views.remove_cart , name='remove_cart'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/' , views.create_order , name = 'create_order'),
    path('detail/<int:order_id>' , views.detail , name = 'detail'),
    path('apply/<int:order_id>' , views.coupon_apply , name= 'coupon_apply'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls' , namespace='cart')),
    path('accounts/',include('accounts.urls' , namespace = 'accounts')),
    path('orders/' , include('orders.urls' , namespace = 'orders')),
    path('',include('products.urls' , namespace = 'products')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class AddCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1 , label= 'Qauntity ' )

cart/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.decorators.http import require_POST
from products.models import Product
from .forms import AddCartForm
from .cartsession import Cart
from django.contrib import messages

def detail(request):
    cart = Cart(request)
    return render(request,'cart/detail.html' , context={'cart':cart})

@require_POST
def add_cart(request , product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = AddCartForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product , quantity = cd['quantity'])
        return redirect ('cart:detail')
        
def remove_cart(request , product_id):
    cart = Cart(request)
    product = get_object_or_404(Product , id = product_id)
    cart.remove(request , product)
    messages.success(request , 'Your product deleted from your cart successfully','success')
    return redirect ('cart:detail')
    

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block title %} Cart {% endblock %}

{% block content %}
<br><br><br>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">PRODUCT</th>
            <th scope="col">CATEGORY</th>
            <th scope="col">BRAND</th>
            <th scope="col">UNIT PRICE</th>
            <th scope="col">QUANTITY</th>
            <th scope="col">TOTAL PRICE</th>
            <th scope="col">REMOVE</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{item.product}}</td>
                <td>{{item.product.category}}</td>
                <td>{{item.product.brand}}</td>
                <td>{{item.price}} $</td>
                <td>{{item.quantity}}</td>
                <td>{{item.total_price}}$</td>
                <td><a href="{% url 'cart:remove_cart' item.product.id %}">Delete</a></td>
            </tr>
        {% endfor %}
        <tr style="color: green;">
            <td colspan="5"></td>
            <td ><h3>TOTAL</h3></td>
            <td ><h3>{{cart.get_total_price}}$</h3></td>
        </tr>
        </tbody>
    </table>

    <a href="{% url 'orders:create_order' %}" class="btn btn-primary">CHECK OUT</a>
{% endblock %}