cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('',views.detail , name='detail'),
    path('add/<int:product_id>/',views.add_cart , name='add_cart'),
    path('remove/<int:product_id>/' , views.remove_cart , name='remove_cart'),
]

products/urls.py
from django.urls import path
from . import views


app_name='products'
urlpatterns=[
    path('',views.home , name='home'),
    path('<slug:slug>/' , views.details , name='details'),
    path('categories/<slug:cslug>/' , views.home , name = 'categories'),
    path('categories/<slug:cslug>/<slug:bslug>/' , views.home , name = 'brand'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls' , namespace='cart')),
    path('accounts/',include('accounts.urls' , namespace = 'accounts')),
    path('orders/' , include('orders.urls' , namespace = 'orders')),
    path('',include('products.urls' , namespace = 'products')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['name',]
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:categories',args=[self.slug,])


class Brand(models.Model):
    category = models.ForeignKey(Category , on_delete = models.CASCADE , related_name='cbrand')
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['name']


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:brand' , args=[self.category.slug , self.slug])

    
class Product(models.Model):
    category = models.ForeignKey(Category , on_delete=models.CASCADE , related_name='Cproduct')
    brand = models.ForeignKey(Brand , on_delete= models.CASCADE , related_name = 'bproduct' , null=True , blank = True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    description = models.TextField()
    price = models.DecimalField(max_digits=7 , decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:details',args=([self.slug]))

products/forms.py
from django import forms

class PriceFilter(forms.Form):
    min = forms.IntegerField()
    max = forms.IntegerField()

products/views.py
from django.shortcuts import render , get_object_or_404
from . models import Product , Category , Brand
from cart.forms import AddCartForm
from . forms import PriceFilter

def home(request , cslug = None , bslug = None):
    if request.method=="POST":
        form = PriceFilter(request.POST)
        if form.is_valid():
            minimum = form.cleaned_data['min']
            maximum = form.cleaned_data['max']
            products = Product.objects.filter(price__gte = minimum , price__lte = maximum , available = True)
    else:
        products = Product.objects.filter(available = True)
        form = PriceFilter()

    categories = Category.objects.all()
    brands = Brand.objects.all()

    if bslug is not None:
        category = get_object_or_404(Category,slug=cslug)
        brand = get_object_or_404(Brand,slug=bslug)
        products = Product.objects.filter(category = category , brand = brand , available = True)
        categories = Category.objects.all()
        brands = Brand.objects.all()
        return render (request , 'products/home.html' , context={'products':products , 'categories':categories , 'brands':brands})

    elif cslug is not None:
        category = get_object_or_404(Category,slug=cslug)
        products = Product.objects.filter(category= category , available = True)
        categories = Category.objects.all()
        brands = Brand.objects.all()
        return render (request , 'products/home.html' , context={'products':products , 'categories':categories , 'brands':brands})
    else:
        return render (request , 'products/home.html' , context={'products':products , 'categories':categories , 'brands':brands , 'form':form})    

def details(request , slug):
    product = get_object_or_404(Product , slug = slug)
    form = AddCartForm()
    return render(request,'products/details.html' , {'product':product , 'form':form})
    

products/templates/products/details.html
{% extends 'base.html' %}

{% block title %} {{product.name|capfirst}} {% endblock %}

{% block content %}
    <h2 style="display: block; text-align: center;">{{product.brand|upper}}</h2>
    <h2 style="display: block; text-align: center; ">{{product.name}}</h2>
    <img src="{{product.image.url}}" alt="{{product.category}}" width="50%" style="display: block; margin-left: auto; margin-right: auto;" ><br>
    <h2 style="display: block; text-align: center; color: red;">PRICE: {{product.price}} $</h2>
    <blockquote class="blockquote text-center">
        <p class="mb-0">{{product.description}}</p>
        <br>
        <footer class="blockquote-footer">{{product.created}}</footer>
    </blockquote>
<hr><br>
<h3 style="color:blueviolet">You can buy {{product.brand}} {{product.name}} {{product.category}} by filling this form</h3> <br>
    <form action="{% url 'cart:add_cart' product.id %}" method ="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" class = 'btn btn-primary' value="Add to cart">
    </form>
{% endblock %}

products/templates/products/home.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %} Radmehr Shop {% endblock %}

{% block content %}
<form action="{% url 'products:home'%}" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" class = 'btn btn-primary' value="filter">
</form>
<div class="dropdown" style="display: block;text-align: center;">
    <p> You can select your category to find out your product easier:</p>
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
        Categories
        </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for cat in categories %}
        <a class="dropdown-item" href="{{cat.get_absolute_url}}">
            <ul>
            {{cat.name}}
            {% for brand in brands %}
                {% if brand.category == cat %}
                    <li>
                        <a href="{{brand.get_absolute_url}}">{{ brand.name }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            </ul>
        </a>
        <div class="dropdown-divider"></div>
    {% endfor %}
    <a class="dropdown-item" href="{% url 'products:home' %}">All products</a>
    </div>
</div>
<br>
{% for product in products %}
    <div class="card" style="width: 18rem; display: inline-block;">
        {% thumbnail product.image "300x300" crop="center" as im %}
            <img src="{{ im.url }}" class="card-img-top" width="{{ im.width }}" height="{{ im.height }}" alt="{{product.category}}">
        {% endthumbnail %}
        <!-- <img class="card-img-top" src="{{product.image.url}}" alt="{{product.category}}"> -->
            <div class="card-body">
                <h5 class="card-title" style ="text-align: center; color:black;">{{product.name}}</h5>
                <p class="card-text" style ="text-align: center; color: red;">{{product.price}}$</p>
                <a href="{{product.get_absolute_url}}" class="btn btn-primary" style ="display:block ;margin-left: auto; margin-right: auto;">More details</a>
            </div>
    </div>
{% endfor %}
{% endblock %}