accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/' , views.user_login , name = 'user_login'),
    path('logout/' , views.user_logout , name = 'user_logout'),
    path('registration/' , views.user_registration , name = 'user_registration'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('',views.detail , name='detail'),
    path('add/<int:product_id>/',views.add_cart , name='add_cart'),
    path('remove/<int:product_id>/' , views.remove_cart , name='remove_cart'),
]

products/urls.py
from django.urls import path
from . import views


app_name='products'
urlpatterns=[
    path('',views.home , name='home'),
    path('<slug:slug>/' , views.details , name='details'),
    path('categories/<slug:cslug>/' , views.home , name = 'categories'),
    path('categories/<slug:cslug>/<slug:bslug>/' , views.home , name = 'brand'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls' , namespace='cart')),
    path('accounts/',include('accounts.urls' , namespace = 'accounts')),
    path('orders/' , include('orders.urls' , namespace = 'orders')),
    path('',include('products.urls' , namespace = 'products')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{message.tags}}">{{message}}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'products:home'%}">Home</a>
    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{%url 'accounts:user_logout'%}">LOG OUT</a>
    <a class="navbar-brand" href="{%url 'cart:detail'%}">MY CART</a>
    {% else %}
      <a class="navbar-brand" href="{%url 'accounts:user_registration'%}">REGISTER</a>
      <a class="navbar-brand" href="{%url 'accounts:user_login'%}">LOG IN</a>
    {% endif %}
  </div>
</nav>